version: "3.9"

networks:
  kafka-net:

volumes:
  kafka-data:

services:

  zookeeper:
    image: zookeeper:3.8
    restart: unless-stopped
    networks: [kafka-net]
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    restart: unless-stopped
    networks: [kafka-net]
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: unless-stopped
    networks: [kafka-net]
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    depends_on:
      - kafka

  ms-producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    image: kafka-ms-producer:1.0.0
    container_name: kafka-ms-producer
    networks: [ kafka-net ]
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  ms-consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    image: kafka-ms-consumer:1.0.0
    container_name: kafka-ms-consumer
    networks: [ kafka-net ]
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8081:8081"
    depends_on:
      - kafka

